config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  resources :posts do
    get :contacts, on: :collection
  end
  resources :pictures, only: [:create, :destroy]
  resources :tags, only: [:show]
  resources :categories




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence:  true
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :post
  mount_uploader :image, ImageUploader
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :pictures
  has_many :taggings
  has_many :tags, through: :taggings
  mount_uploader :image, ImageUploader
  validates :title, :summary, :body, presence: true

  def all_tags
    self.tags.map(&:name).join(', ')
  end

  def all_tags=(names)
    self.tags = names.split(',').map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :posts, through: :taggings

  def self.counts
    self.select("name, count(taggings.tag_id) as count").joins(:taggings).group('taggings.tag_id')
  end
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session, if: ->{request.format.json?}

  add_flash_types :success, :danger, :info, :warning
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :set_category, only: [:update, :show, :destroy, :edit]

  def index
    @categories = Category.all
  end

  def show

  end

  def new
    @category = Category.new
    # @category = Category.find(params[:id])
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path, success: 'Категория успешно создана'
    else
      flash[:danger] = 'Категория не создана'
      render :new
    end
  end

  def edit

  end

  def update
    if @category.update_attributes(category_params)
      redirect_to categories_path, success: 'Категоря успешно обновлена'
    else
      flash[:danger] = 'Категория не обновлена'
      render :update
    end
  end

  def destroy
    @category.destroy
    redirect_to posts_path, success: 'Категория удалена'
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def set_category
    @category = Category.find(params[:id])
  end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def create
    @picture = Picture.new(image_params)
    @picture.save
    respond_to do |format|
      format.json { render :json => { url: @picture.image.url(:large), picture_id: @picture.id } }
    end
  end

  def destroy
    picture = Picture.find(params[:id])
    picture.destroy
    respond_to do |format|
      format.json { render json: { status: :ok } }
    end
  end

  private

  def image_params
    params.require(:picture).permit(:image)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post, only: [:show, :edit, :destroy, :update]

  def index
    @posts = Post.paginate(:page => params[:page], per_page: 10)
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new( post_params )

    if @post.save
      redirect_to @post, success: 'Статья создана'
    else
      flash[:danger] = 'Статья не сохранена'
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update_attributes( post_params )
      redirect_to @post, info: 'Статья успешно обновлена'
    else
      flash[:danger] = 'Статься не обновлена'
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, success: 'Статья удалена'
  end

  def contacts

  end

  private

  def post_params
    params.require(:post).permit(:title, :summary, :body, :image, :all_tags)
  end

  def set_post
    @post = Post.find(params[:id])
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.find_by(name: params[:id])
    @post = @tag.posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def tag_cloud(tags, classes)
    max = tags.sort_by(&:count).last
      tags.each do |tag|
        index = tag.count.to_f / max.count * (classes.size-1)
        yield(tag,classes[index.round])
      end
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/categories/_form.html.erb
<% if @category.errors.any? %>
    <div class="alert alert-dismissible">
      <h5><%= t('common.errors') %></h5>
      <ul>
        <% @category.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>

<!--TODO узнать как вывесит в паршал-->

<%= form_for @category do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

    <div class="form-group">
      <%= f.submit t('.save', action: @category.new_record? ? 'Сохранить' : 'Изменить'), class: 'btn btn-primary' %>
      <%= link_to t('common.back'), :back, class: 'btn btn-outline-secondary' %>
    </div>
<% end %>

app/views/categories/edit.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1><%= t('.title') %></h1>

<div class="button_panel">
  <%= link_to 'Новая категория', new_category_path, class: 'btn btn-outline-primary btn-sm' %>
</div>

<section id="categories">
  <table class="table">
    <thead>
    <tr>
      <th>#</th>
      <th>Название</th>
      <th></th>
    </tr>
    </thead>
    <tbody>
      <% @categories.each_with_index do |category, index|  %>
        <tr>
          <td>  <%= index + 1 %></td>
          <td><%= category.name %></td>
          <td>
            <%= link_to t('posts.show.edit'), edit_category_path(category), class: 'btn btn-outline-primary btn-sm' %>
            <%= link_to t('posts.index.post.delete'), category_path(category), method: :delete, data: {confirm: 'Вы уверены?'}, class: 'btn btn-outline-danger btn-sm' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</section>

app/views/categories/new.html.erb
<h1> <%= t('.title') %> </h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<h1> <%= t('.title') %> </h1>
<div>
  <%= @category.name %>
</div>

<%= link_to t('.edit'), edit_category_path(@category) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="navbar navbar-default">
          <div class="container navbar-container">
            <div class="navbar-header">
              <a class="navbar-brand" href="#"><%= link_to 'Статьи', posts_path %></a>
            </div>
            <div class="navbar-header ">
              <%= link_to 'Контакты', contacts_posts_path, class: 'navbar-brand' %>
            </div>
            <ul class="nav navbar-nav">
              <li class="active"><a href="#"><%= link_to 'Новая статья', new_post_path %></a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="container main">
      <div class="row">
        <div class="col-md-8">
          <% flash.each do |name, message| %>
          <div class="alert alert-<%= name %>">
            <%= message %>
          </div>
          <% end %>
          <%= yield %>
        </div>
        <div class="col-md-4">
          <% tag_cloud(Tag.counts, %w{tag1 tag2 tag3 tag4 tag5}) do |tag, css_class| %>
            <%= link_to tag.name,tag_path(tag.name), class: css_class %>
          <% end %>
        </div>
      </div>
    </div>
  </div>


  </body>
</html>

app/views/posts/_delimeter.html.erb
<div class="page_delimeter"> <%= params[:page] %> </div>

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>

    /**
     *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
     *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
    /*
     var disqus_config = function () {
     this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
     this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
     };
     */

    var disqus_config = function () {
        this.page.url = 'http://localhost.com<%= request.original_fullpath %>';  // Replace PAGE_URL with your page's canonical URL variable
        this.page.identifier = '<%= @post.id %>'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };

    (function() { // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        s.src = 'https://learn-rails-from-youtube.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
    <div class="alert alert-dismissible">
      <h5><%= t('common.errors') %></h5>
      <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

<%= form_for @post, html: { multipart: true } do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

    <div class="form-group">
      <%= f.label :summary %>
      <%= f.text_area :summary, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :body %>
      <%= f.trix_editor :body, class: 'trix-editor' %>
    </div>

    <div class="form-group">
      <%= f.label :all_tags %>
      <%= f.text_field :all_tags, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :image %>
      <%= f.file_field :image, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.submit t('.save', action: @post.new_record? ? 'Сохранить' : 'Изменить'), class: 'btn btn-primary' %>
      <%= link_to t('common.back'), :back, class: 'btn btn-outline-secondary' %>
    </div>


<% end %>

app/views/posts/_post.html.erb
<article class="post">
  <sections class="post-head">
    <h2><%= link_to post.title, post_path(post) %></h2>
    <div> <%= image_tag post.image.url(:thumb), class: 'img-show' if post.image? %> </div>
    <small>
      <time><%= post.created_at.to_date.strftime("%d %B, %Y") %></time>
      |
      <%= link_to t('posts.index.post.edit'), post_path(post) %>
      |
      <%= link_to t('posts.index.post.delete'), post_path(post), method: :delete, data: {confirm: 'Вы уверены?'} %>
    </small>
  </sections>
  <sections class="post-summary">
    <%= post.summary %>
  </sections>
  <section class="footer-summary">
      <%= raw post.tags.map(&:name).map{ |t| link_to t, tag_path(t), class: 'badge badge-primary'}.join(' ') %>
  </section>
</article>

app/views/posts/contacts.html.erb
<h1>Contacts</h1>
<p>tel: 8800 000 0000</p>
<p>Adress: Puhkina 3, Novokuznetsk</p>

app/views/posts/edit.html.erb
<h1> <%= t('.title')+' ' %><%=  @post.title %></h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<h1><%= t('.title') %></h1>
<section id='posts'>
  <%= render @posts %>
</section>

<%= will_paginate @posts, renderer: 'BootstrapPaginationHelper::LinkRenderer' %>

app/views/posts/index.js.erb
$('#posts').append("<%= j render(partial: 'delimeter') %>");
$('#posts').append("<%= j render(@posts) %>");

<% if @posts.next_page %>
    $('.pagination').replaceWith("<%= j  will_paginate(@posts, renderer: 'BootstrapPaginationHelper::LinkRenderer') %>");
<% else %>
    $('.pagination').remove();
<% end %>

app/views/posts/new.html.erb
<h1><%= I18n.t('posts.new.title') %></h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<section class="post-head">
  <h1><%= t('.title').to_s + ' '+ @post.title.to_s %></h1>
  <p><%= link_to t('.edit'), edit_post_path(@post) %></p>
  <p><%= link_to t('.delete'), post_path(@post) ,method: :delete, data: { confirm: 'Вы уверены?'} %></p>
  <p> <%= image_tag @post.image.url(:large), class: 'img-show' if @post.image? %> </p>
</section>
<section class="post-summary">
  <%= @post.body.html_safe %>
</section>
<section>
  <%= render 'disqus' %>
</section>

app/views/tags/show.html.erb
<h1><%= @tag.name %></h1>
<% if @tag.posts.empty? %>
    <h2>Статей нет</h2>
<% else %>
  <%=  render @tag.posts %>
<% end %>